events {}

http {
    server {
        listen 80;

        # 1. Frontend: Todo el tráfico base va a React
        location / {
            proxy_pass http://frontend:80; # Asumiendo que el Frontend correrá en el 80 interno
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Backend: Cualquier ruta con /api/ va hacia Java Spring Boot
        location /api/ {
            proxy_pass http://backend:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Para subida de videos (No limitar el tamaño a 1MB estándar)
            client_max_body_size 500M;
        }

        # 3. Datos de la IA: Servir los videos procesados (thumbnails y finales) transparentemente
        location /data/ {
            proxy_pass http://ai:8000/data/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
