spring.application.name=scalevision-backend
# Server
server.port=8080

# H2 (desarrollo local)
spring.datasource.url=jdbc:h2:mem:scalevisiondb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Integracion IA
ai.service.base-url=${AI_SERVICE_URL:http://localhost:8000/svmvp}
ai.callback.schema-version=${AI_CALLBACK_SCHEMA_VERSION:1.0.0}

